apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-servers-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: apache
        namespace: apache
        repoPath: apache
      - name: nginx
        namespace: nginx
        repoPath: nginx
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: myproj
      source:
        repoURL: https://github.com/amitopenwriteup/argocdlistgit.git
        targetRevision: HEAD
        path: '{{repoPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
